/*   This file is part of LibAAVE.
 * 
 *   LibAAVE is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   LibAAVE is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with LibAAVE.  If not, see <http://www.gnu.org/licenses/>.
 *
 *   Copyright 2013 André Oliveira, Nuno Silva, Guilherme Campos,
 *   Paulo Dias, José Vieira/IEETA - Universidade de Aveiro
 *
 *
 *   libaave/hrtf_listen.c: audio processing with LISTEN HRTF set
 */

/**
 * @file hrtf_listen.c
 *
 * The hrtf_listen.c file implements the interface to use the LISTEN
 * (IRCAM/AKG) HRTF set. To select this set for the auralisation process,
 * call aave_hrtf_listen() after initialising the aave structure and
 * before calling aave_put_audio().
 *
 * The LISTEN HRTF set consists of head-related impulse responses (HRIR) of
 * 51 subjects. This interface admits using one of them at a time, chosen
 * at compile time. Each HRIR is 512 samples long at 44100Hz (~11.6ms).
 *
 * For each subject, HRIR measurements are available for the following
 * elevations: -45, -30, -15, 0, 15, 30, 45, 60, 75 and 90 degrees.
 * Currently, this interface does not support elevations 60, 75 and 90.
 * The azimuths available are from -180 to 180 degrees, in 15 degree steps.
 *
 * References:
 * http://recherche.ircam.fr/equipes/salles/listen/
 */

#include "aave.h"

/** The HRTF set, generated by tools/hrtf_listen_set.c (subject 1040). */
extern const float hrtf_listen_set_1040[][2][2048];

/**
 * Get the closest HRTF pair for the specified coordinates.
 * @p elevation is [-90;90] degrees. @p azimuth is [-180;180] degrees.
 * @p hrtf[0] will be the left HRTF, @p hrtf[1] the right HRTF.
 */
static void aave_hrtf_listen_get(const float *hrtf[2], int elevation, int azimuth)
{
	unsigned i;

	azimuth = -azimuth;
	if (azimuth < 0)
		azimuth += 360;

	if (elevation < -45)
		elevation = -45;
	else if (elevation > 45)
		elevation = 45;

	/** @todo Elevations 60, 75 and 90. */

	i = (elevation + 45) / 15 * 24 + azimuth / 15;

	hrtf[0] = hrtf_listen_set_1040[i][0];
	hrtf[1] = hrtf_listen_set_1040[i][1];
}

/**
 * Select the LISTEN HRTF set for the auralisation process.
 */
void aave_hrtf_listen(struct aave *a)
{
	a->hrtf_frames = 512;
	a->hrtf_get = aave_hrtf_listen_get;
	a->hrtf_output_buffer_index = 0;
}
