/*   This file is part of LibAAVE.
 * 
 *   LibAAVE is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   LibAAVE is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with LibAAVE.  If not, see <http://www.gnu.org/licenses/>.
 *
 *   Copyright 2013 André Oliveira, Nuno Silva, Guilherme Campos,
 *   Paulo Dias, José Vieira/IEETA - Universidade de Aveiro
 *
 *
 *   libaave/hrtf_cipic.c: audio processing with CIPIC HRTF set
 */

/**
 * @file hrtf_cipic.c
 *
 * The hrtf_cipic.c file implements the interface to use the CIPIC HRTF set.
 * To select this set for the auralisation process, call aave_hrtf_cipic()
 * after initialising the aave structure and before calling aave_put_audio().
 *
 * The CIPIC HRTF set consists of head-related impulse responses (HRIR)
 * of 45 subjects. This interface admits using one of them at a time,
 * chosen at compile time.
 *
 * For each subject, HRIR measurements are available for 64 elevations
 * in 5.625 degree steps (360/64) and the following azimuths:
 * -80, -65, -55, -45 to 45 in 5 degree steps, 55, 65 and 80 degrees.
 * This interface supports all azimuths, but currently only elevation 0.
 *
 * Each HRIR is 200 samples long at 44100Hz (~4.5ms). Because the discrete
 * Fourier transform (DFT) implemented in dft.h is optimized for powers of 2,
 * each HRIR is zero-padded to 256 samples for use in this interface.
 *
 * References:
 * V. R. Algazi, R. O. Duda, D. M. Thompson and C. Avendano,
 * "The CIPIC HRTF Database",
 * Proc. 2001 IEEE Workshop on Applications of Signal Processing
 * to Audio and Electroacoustics, pp. 99-102,
 * Mohonk Mountain House, New Paltz, NY, Oct. 21-24, 2001.
 */

#include "aave.h"

/** The subject of the CIPIC HRTF set to use (subject 008). */
#define hrtf_cipic_set hrtf_cipic_set_008

/** The HRTF set, generated by tools/hrtf_cipic_set.c (subject 008). */
extern const float hrtf_cipic_set_008[][1024];

/**
 * Get the closest HRTF pair for the specified coordinates.
 * @p elevation is [-90;90] degrees. @p azimuth is [-180;180] degrees.
 * @p hrtf[0] will be the left HRTF, @p hrtf[1] the right HRTF.
 *
 * Currently, all elevations map to elevation 0.
 * @todo Use all elevation measures available, not just 0 degrees.
 */
static void aave_hrtf_cipic_get(const float *hrtf[2], int elevation, int azimuth)
{
	if (azimuth <= -80) {
		hrtf[0] = hrtf_cipic_set[0];
		hrtf[1] = hrtf_cipic_set[1];
	} else if (azimuth <= -65) {
		hrtf[0] = hrtf_cipic_set[2];
		hrtf[1] = hrtf_cipic_set[3];
	} else if (azimuth <= -55) {
		hrtf[0] = hrtf_cipic_set[4];
		hrtf[1] = hrtf_cipic_set[5];
	} else if (azimuth <= -45) {
		hrtf[0] = hrtf_cipic_set[6];
		hrtf[1] = hrtf_cipic_set[7];
	} else if (azimuth <= -40) {
		hrtf[0] = hrtf_cipic_set[8];
		hrtf[1] = hrtf_cipic_set[9];
	} else if (azimuth <= -35) {
		hrtf[0] = hrtf_cipic_set[10];
		hrtf[1] = hrtf_cipic_set[11];
	} else if (azimuth <= -30) {
		hrtf[0] = hrtf_cipic_set[12];
		hrtf[1] = hrtf_cipic_set[13];
	} else if (azimuth <= -25) {
		hrtf[0] = hrtf_cipic_set[14];
		hrtf[1] = hrtf_cipic_set[15];
	} else if (azimuth <= -20) {
		hrtf[0] = hrtf_cipic_set[16];
		hrtf[1] = hrtf_cipic_set[17];
	} else if (azimuth <= -15) {
		hrtf[0] = hrtf_cipic_set[18];
		hrtf[1] = hrtf_cipic_set[19];
	} else if (azimuth <= -10) {
		hrtf[0] = hrtf_cipic_set[20];
		hrtf[1] = hrtf_cipic_set[21];
	} else if (azimuth <= -5) {
		hrtf[0] = hrtf_cipic_set[22];
		hrtf[1] = hrtf_cipic_set[23];
	} else if (azimuth <= 0) {
		hrtf[0] = hrtf_cipic_set[22];
		hrtf[1] = hrtf_cipic_set[23];
	} else if (azimuth <= 5) {
		hrtf[0] = hrtf_cipic_set[23];
		hrtf[1] = hrtf_cipic_set[22];
	} else if (azimuth <= 10) {
		hrtf[0] = hrtf_cipic_set[21];
		hrtf[1] = hrtf_cipic_set[20];
	} else if (azimuth <= 15) {
		hrtf[0] = hrtf_cipic_set[19];
		hrtf[1] = hrtf_cipic_set[18];
	} else if (azimuth <= 20) {
		hrtf[0] = hrtf_cipic_set[17];
		hrtf[1] = hrtf_cipic_set[16];
	} else if (azimuth <= 25) {
		hrtf[0] = hrtf_cipic_set[15];
		hrtf[1] = hrtf_cipic_set[14];
	} else if (azimuth <= 30) {
		hrtf[0] = hrtf_cipic_set[13];
		hrtf[1] = hrtf_cipic_set[12];
	} else if (azimuth <= 35) {
		hrtf[0] = hrtf_cipic_set[11];
		hrtf[1] = hrtf_cipic_set[10];
	} else if (azimuth <= 40) {
		hrtf[0] = hrtf_cipic_set[9];
		hrtf[1] = hrtf_cipic_set[8];
	} else if (azimuth <= 45) {
		hrtf[0] = hrtf_cipic_set[7];
		hrtf[1] = hrtf_cipic_set[6];
	} else if (azimuth <= 55) {
		hrtf[0] = hrtf_cipic_set[5];
		hrtf[1] = hrtf_cipic_set[4];
	} else if (azimuth <= 65) {
		hrtf[0] = hrtf_cipic_set[3];
		hrtf[1] = hrtf_cipic_set[2];
	} else { /* azimuth <= 80 */
		hrtf[0] = hrtf_cipic_set[1];
		hrtf[1] = hrtf_cipic_set[0];
	}
}

/**
 * Select the CIPIC HRTF set for the auralisation process.
 */
void aave_hrtf_cipic(struct aave *a)
{
	a->hrtf_frames = 256;
	a->hrtf_get = aave_hrtf_cipic_get;
	a->hrtf_output_buffer_index = 0;
}
